### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by fancythedeveloper** [SunakazeKun/riivo2dolphin#1]
After a bit, I got it to make INI files, but now, what do I do? Do I put them into /User/GameSettings (or /Dolphin Emulator/GameSettings if no portable.txt)? And where do I put the general mod pack in?

**Comment by eddmanx** [comment]
@SunakazeKun 
Any suggestions? I also can't tell how the ini is supposed to be used.

**Comment by SunakazeKun** [comment]
You put them in GameSettings, yes. And the filename has to be the game's ID. For example SB4P01.ini would contain all the patches for PAL Super Mario Galaxy 2.

**Comment by eddmanx** [comment]
It didn't work. These are the riivolution xml and the converted ini file.

https://drive.google.com/file/d/14VIrfld6mJ3Sz7fAE5d3MkyEOOapruf7/view?usp=sharing

I put the ini in `Documents\Dolphin Emulator\GameSettings`, along with the mod folder:

https://i.imgur.com/aBeulbA.jpg
https://i.imgur.com/tQexg7l.jpg

Is your converter compatible with file patching, or only does memory patching?

**Comment by SunakazeKun** [comment]
It only does memory patching
